= Programming Languages
:keywords: programming, languages, paradigms
:toc:
:hide-uri-scheme:
:stylesheet: ../style.css
:linkcss:

.TODO
[%collapsible]
====
. https://en.wikipedia.org/wiki/History_of_programming_languages
. [The Architecture of Open Source Applications](https://aosabook.org/en/)
. https://exercism.org/
. https://www.cs.rochester.edu/~scott/pragmatics/[Programming Language Pragmatics]
. https://dl.acm.org/doi/10.1145/359576.359579[1978, John Backus, Can programming be liberated from the von Neumann style?: a functional style and its algebra of programs]
. https://dl.acm.org/doi/10.1145/358896.358899[1980, Kenneth E. Iverson, Notation as a tool of thought]
. https://dl.acm.org/doi/10.1145/3520306.3534504[2022, Conor Hoekstra, Combinatory logic and combinators in array languages]
. https://youtube.com/playlist?list=PLVFrD1dmDdvdvWFK8brOVNL7bKHpE-9w0[Structure and Interpretation of Computer Programs - YouTube playlist by @code_report]
. https://youtube.com/playlist?list=PLVFrD1dmDdvcjCQDPhExqP56jqxp0Ssn_[Category Theory for Programmers - YouTube playlist by @code_report]
. https://youtube.com/playlist?list=PLVFrD1dmDdvdv7trr5j9ir7qrFK5K80X0[Seven Languages in Seven Weeks - YouTube playlist by @code_report]
. https://en.wikipedia.org/wiki/Type_class
. https://en.wikipedia.org/wiki/Tacit_programming
. https://aplwiki.com/wiki/Train
. https://docs.modular.com/mojo/
. https://www.uiua.org/
. https://www.info.ucl.ac.be/~pvr/VanRoyChapter.pdf[Programming Paradigms for Dummies: What Every Programmer Should Know]
. https://people.inf.ethz.ch/wirth/AD.pdf[Algorithms and Data Structures by Niklaus Wirth]
====

== Start Programming

If you are new to programming I would recommend you to start with Python or TypeScript.
They are both multi-paradigm high-level languages.
Which means you can do basically anything with them relatively easily.
Also they are 2nd and 4th in https://octoverse.github.com/2022/top-programming-languages[GitHub's Top languages used in 2022] ranking.
And 6th, 4th in the https://survey.stackoverflow.co/2022/#most-loved-dreaded-and-wanted-language-love-dread[Stack Overflow's most loved language] ranking.

== https://en.wikipedia.org/wiki/List_of_programming_languages_by_type[Types of Programming Languages]

So far I have found these categories to be the most useful.

Main use::
* General-purpose
* Interactive mode languages
* Command-line interface languages
* System languages
* Machine languages
* Extension languages
* Numerical analysis
* Concurrent languages

Execution::
* Compiled languages
* Interpreted languages

Syntax::
* Curly-bracket languages
* Off-side rule languages

https://en.wikipedia.org/wiki/Programming_paradigm[Paradigm]::
* Multiparadigm languages
* Imperative languages
** Procedural languages
** Object-oriented class-based languages
* Declarative languages
** Functional languages
*** Purely-functional
** Logic-based languages
* Array languages
* Metaprogramming languages

Memory::
* Languages with manual memory management
* Garbage collected languages
* Type safe languages

https://en.wikipedia.org/wiki/Type_system[Type Systems]::
* Strong or Weak
* Static or Dynamic

https://en.wikipedia.org/wiki/Evaluation_strategy[Evaluation strategy]::
* Eager evaluation
* Lazy evaluation
* Short-circuit evaluation

=== First-class Citizen

"In programming language design, a *first-class* citizen (also type, *object*, entity, or *value*) in a given programming language is an entity which supports all the operations generally available to other entities. These operations typically include being *passed as an argument*, *returned from a function*, and *assigned to a variable*."
-- https://en.wikipedia.org/wiki/First-class_citizen

== Languages Worth Mentioning

=== https://en.wikipedia.org/wiki/Assembly_language[Assembly language]

First abstraction above machine code.

=== https://en.wikipedia.org/wiki/System_programming_language[System languages]

https://en.wikipedia.org/wiki/C_(programming_language)[C]::
One of the most successful languages of all time.
I believe, most of the programming languages are written in the C language.
You can sense C's at the time popularity from the song https://youtu.be/1S1fISh-pag[Write in C].

https://go.dev/[Go]::
"Go is a statically typed, compiled high-level programming language designed at Google by Robert Griesemer, Rob Pike, and Ken Thompson."
-- https://en.wikipedia.org/wiki/Go_(programming_language)[]

https://www.rust-lang.org/[Rust]::
The most loved programming language.
Memory safety is done by borrow checker.
Is another language that made it to the Linux kernel source code.

=== https://en.wikipedia.org/wiki/List_of_command-line_interpreters[Command-line interpreters]

link:zsh[Z shell]::
Z Shell is a great option for interactive login shell, extends the Bourne Shell.

=== https://en.wikipedia.org/wiki/JavaScript[JavaScript]

The programming language of the web.

=== https://en.wikipedia.org/wiki/General-purpose_programming_language[General-purpose programming language]

https://www.python.org/[Python]::
Second most used programming language with very pleasant syntax.

https://www.typescriptlang.org/[TypeScript]::
Typed superset of JavaScript developed by Microsoft.

https://www.raku.org/[Raku]::
Formerly called Perl 6.
When regular expressions are not powerful enough, look at Raku's https://docs.raku.org/language/grammar_tutorial.html[Grammars].

=== https://en.wikipedia.org/wiki/Purely_functional_programming[Purely functional]

link:haskell[Haskell]::
Lazily evaluated purely-functional language with type classes.

https://www.idris-lang.org/[Idris2]::
Idris is a programming language designed to encourage Type-Driven Development.

=== https://en.wikipedia.org/wiki/Array_programming[Array oriented]

https://julialang.org/[Julia]::
Great (array) language for mathematics that runs fast (jit).

link:bqn[BQN]::
Iversonian language, by Marshall Lochbaum who started in J and implemented a lot of Dyalog APL himself.
