= Conda
:stylesheet: ../../style.css
:linkcss:
:hide-uri-scheme:

"Package, dependency and environment management for any language—Python, R, Ruby, Lua, Scala, Java, JavaScript, C/ C++, Fortran, and more."
-- https://docs.conda.io/en/latest/

== https://docs.conda.io/projects/conda/en/latest/user-guide/cheatsheet.html[Conda Cheatsheet]

== https://docs.conda.io/projects/conda/en/latest/user-guide/install/linux.html[Installation]

.Anaconda or Miniconda?
[quote,'https://conda.io/projects/conda/en/latest/user-guide/install/download.html#anaconda-or-miniconda']
____
Choose Anaconda if you:

* Are new to conda or Python.
* Like the convenience of having Python and over 1,500 scientific packages automatically installed at once.
* Have the time and disk space---a few minutes and 3 GB.
* Do not want to individually install each of the packages you want to use.
* Wish to use a set of packages curated and vetted for interoperability and usability.

Choose Miniconda if you:

* Do not mind installing each of the packages you want to use individually.
* Do not have time or disk space to install over 1,500 packages at once.
* Want fast access to Python and the conda commands and you wish to sort out the other programs later.
____

"Miniconda is a free minimal installer for conda. It is a small, bootstrap version of Anaconda that includes only conda, Python, the packages they depend on, and a small number of other useful packages, including pip, zlib and a few others."
-- https://docs.conda.io/en/latest/miniconda.html

NOTE::
If you don't want Conda to automatically activate the base environment, run:

    conda config --set auto_activate_base false

== https://conda.io/projects/conda/en/latest/user-guide/getting-started.html[Getting Started]

== https://conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html[Managing Environments]

.Example of environment creation, activation, listing, deactivation and deletion.
[source,console]
----
conda create --name env-name python=3.9
conda activate env-name
conda env list
conda deactivate
conda remove --name env-name --all
----
