= Advices Based on My Life
Jaroslav Langer
:keywords: values, principles, advices
:sectnums:
:linkcss:
:stylesheet: ./../../style.css

== Treat your Ego as if it was a beautiful stupid lovely kid.

== Most of the things you think that matter, don't matter.

== Acknowledge your fears and carefully overcome them little by little.

== Recognize the value of other people and nurture good relationships with them.

== Listen truly what other people say, speech is silver, silence is golden.

== Try to reconcile what others think of you with what you think of yourself.

== Keep in mind that anything you think you know may be wrong.

== Bear in mind that the people around you may be wrong as well.

== Argue only if you can learn something, remember that the wiser retreats.

== Learn to temper your emotions after they have swung one way or another.

== Learn to estimate required time and money well.

== Be honest with yourself and others, pretending of anything harms you the most.

[%collapsible]
====
For example, imagine you need something from a person and you call them.
Start the call by saying what you need to say first.
Don't fool them around so you can later sneak it in.
Just say "Hi, Person's Name, can you do That for me?"
Then you can carry on with the nice stuff for as long as you want.
The point is, you shouldn't put more pressure on a person by sugar-coating them first.
So the other person can decide for themselves.
If they decide to do it without pressure from you, they'll probably feel good about it.
On the other hand, if you make them do it, they're probably not going to like it very much.
If you're being manipulated, you might not know it right away, but you'll know it eventually.
Because if you're doing something you don't want to do, you will know it.
That's just the other person's point of view.
With this approach, you can be rejected more often.
However, your relationship with others will be much better.
====

== Enjoy the praise and let its glow fall on as many people as possible.

== Don't ignore things that are unpleasant, face them with humility.

== Be careful about people who say they know the meaning of your life, they lie.

== Boredom is a great environment for your mind to be creative.

== Be nice to yourself, the best you can do is to try to be better than yesterday.

== You can never be too kind.

== Accept your emotions, they are not inevitable reactions, they are your product.

[%collapsible]
====
A lot of your emotions are the result of your imperfectly balanced hormonal system.
Naturally, you come up with many reasons and explanations for having them.
Start by accepting them.
Once you're okay with your emotions, start thinking about them, not before.
====
