= Data
:keywords: data, text, format, csv, yaml, json, xml, html, tex, asciidoc, markdown
:hide-uri-scheme:
:toc:
:source-highlighter: highlight.js
:stylesheet: ../style.css
:linkcss:

== About

Text formats suitable for storage and transfer of structured data::
* csv
* yaml
* toml
* xml
* json
* xls
Markup formats::
* html
* markdown
* asciidoc
* rst
* tex

== File Encoding

=== BOM

"The byte order mark (BOM) is a particular usage of the special Unicode character, U+FEFF BYTE ORDER MARK"
-- https://en.wikipedia.org/wiki/Byte_order_mark

.UTF-8 BOM
----
0xEF,0xBB,0xBF
----

.UTF-16 BOM
----
U+FEFF
----

== Conversion Between Formats

Good format specification allows to convert the document from one format to another.
It can be done automatically using a conversion tool.
When the target format has equal or greater expression power the conversion is lossless.

link:pandoc[Pandoc]::
A universal document converter.

== How to Organize Data

Tree::
Overview of directories, high level overview.
Directory/Folder::
Container for related files and subdirectories.
Index::
File describing the directory.
Labels/Tags/Keywords::
Metadata attached to files or directories, useful for cross directory orientation.
Contents/Table of Contents::
Overview of document sections, also useful for orientation and quick summary.
Links/References::
Useful for cross document orientation.
Composition/Includes::
Useful for full body search, big overview and export purposes.
Tool Automations::
* Tree generated based on the structure of the directories.
* Index generated based on the files in the directory.
* Contents generated based on the document headers.
* Label search for files and directories.
* Composition of multiple documents.
* Document export into different formats.
