= English Language
:hide-uri-scheme:
:toc: right

== Conditionals

The Zero Conditional::
* (if + present simple, ... present simple)
* If you heat water to 100 degrees, it boils.

The First Conditional::
* (if + present simple, ... will + infinitive)
* If it rains tomorrow, we'll go to the cinema.

The Second Conditional::
* (if + past simple, ... would + infinitive)
* If I had a lot of money, I would travel around the world.

The Third Conditional::
* (if + past perfect, ... would + have + past participle)
* If I had gone to bed early, I would have caught the train.

Examples are taken from https://www.perfect-english-grammar.com/conditionals.html

== That (Who, When, Where) vs. Which

That (Who, When, Where)::
The general rule requires that you use that only to introduce a restrictive (or defining) relative clause, which identifies the person or thing being talked about.
Which::
On the other hand, use which with non-restrictive (or non-defining) clauses. These are clauses providing additional information about something that has already been identified in the context. In this use, which is always preceded by a comma and a comma is placed after the restrictive clause ends (if the sentence continues).

The explanations are taken from https://www.diffen.com/difference/That_vs_Which

== Parentheses Brackets Braces

    (parentheses)
    [brackets]
    {braces}

https://practicaltypography.com/parentheses-brackets-and-braces.html
