= Software Tools
:keywords: operation-system, desktop-environment, browser, terminal, terminal-emulator, shell, text-editor, git, programming
:experimental:
:hide-uri-scheme:
:toc:
:stylesheet: ./../style.css
:linkcss:

The art of using a computer like a human.

== Index

* link:cascading-style-sheets[]
* link:docker[]
* link:docsify[]
* link:git[]
* link:github[]
* link:hugo[]
* link:jupyter-notebook[]
* link:make[]
* link:neovim[]
* link:regular-expressions[]
* link:unix[]
* link:vim[]

== Operating System

Right now I am using Debian GNU/Linux distribution "testing".
It combines the availability of regular stuff with the power of rolling releases.

=== Linux Kernel

.Definition
[%collapsible]
====
[quote, 'https://en.wikipedia.org/wiki/Kernel_(operating_system)']
____
The kernel is a computer program at the core of a computer's operating system and generally has complete control over everything in the system.[1] It is the portion of the operating system code that is always resident in memory[2] and facilitates interactions between hardware and software components. A full kernel controls all hardware resources (e.g. I/O, memory, cryptography) via device drivers, arbitrates conflicts between processes concerning such resources, and optimizes the utilization of common resources e.g. CPU & cache usage, file systems, and network sockets. On most systems, the kernel is one of the first programs loaded on startup (after the bootloader). It handles the rest of startup as well as memory, peripherals, and input/output (I/O) requests from software, translating them into data-processing instructions for the central processing unit.
____
====

https://en.wikipedia.org/wiki/Linux_kernel

=== GNU Core Utilities

"The GNU Core Utilities or coreutils is a package of GNU software containing implementations for many of the basic tools, such as cat, ls, and rm, which are used on Unix-like operating systems."
-- https://en.wikipedia.org/wiki/GNU_Core_Utilities

== GNU/Linux Distributions

=== Debian

"Debian (/ˈdɛbiən/),[5][6] also known as Debian GNU/Linux, is a Linux distribution composed of free and open-source software, developed by the community-supported Debian Project, which was established by Ian Murdock on August 16, 1993."
-- https://en.wikipedia.org/wiki/Debian

=== Debian Testing

"Debian testing is the current development state of the next stable Debian distribution. It is also made available under the code name of the next stable release,"
-- https://wiki.debian.org/DebianTesting

=== Linux Mint

"Linux Mint is a community-driven Linux distribution based on Ubuntu (which is in turn based on Debian), bundled with a variety of free and open-source applications."
-- https://en.wikipedia.org/wiki/Linux_Mint

=== Manjaro

"Manjaro (/mænˈdʒɑːroʊ/ man-JAAR-oh) is a free and open-source Linux distribution based on the Arch Linux operating system that has a focus on user-friendliness and accessibility. It uses a rolling release update model and Pacman as its package manager."
-- https://en.wikipedia.org/wiki/Manjaro

== Windowing system

"In computing, a windowing system (or window system) is software that manages separately different parts of display screens.[1] It is a type of graphical user interface (GUI) which implements the WIMP (windows, icons, menus, pointer) paradigm for a user interface."
-- https://en.wikipedia.org/wiki/Windowing_system

Currently I use the https://www.x.org/wiki/[X11], I am curious about the https://wayland.freedesktop.org/[Wayland].

.Tell me which Display Server is running?
[source,sh]
----
echo $XDG_SESSION_TYPE
----

== Desktop environment

At this moment I am using Xfce and my plan is to switch back to GNOME.

=== GNOME

"GNOME (/ɡəˈnoʊm, ˈnoʊm/),[6][7][8] originally an acronym for GNU Network Object Model Environment, is a free and open-source desktop environment for Linux and other Unix-like[9] operating systems."
-- https://en.wikipedia.org/wiki/GNOME

=== Cinnamon

"Cinnamon is a free and open-source desktop environment for Linux and Unix-like operating systems, deriving from GNOME 3 but following traditional desktop metaphor conventions."
-- https://en.wikipedia.org/wiki/Cinnamon_(desktop_environment)

=== Xfce

"Xfce or XFCE (pronounced as four individual letters)[3] is a free and open-source desktop environment for Linux and other Unix-like operating systems."
-- https://en.wikipedia.org/wiki/Xfce

=== KDE

"KDE Plasma 5 is the fifth and current generation of the graphical workspaces environment created by KDE primarily for Linux systems. KDE Plasma 5 is the successor of KDE Plasma 4 and was first released on 15 July 2014."
-- https://en.wikipedia.org/wiki/KDE_Plasma_5

== Terminal Emulator

I just use what is installed.
https://larbs.xyz/[Luke Smith] uses https://st.suckless.org/.
I am curious about https://github.com/alacritty/alacritty/[alacritty].

=== Window manager

At this time I don't use any terminal window manager.

* tmux
* i3
* dwm

=== File manager

I don't typically use a terminal file manager, except for *netrw* within Neovim.

* ranger
* lf

== Shell

Currently I use bash and I my plan is to switch to zsh.

. Bash

== Shell Prompt

I use the default, modified with a git branch.

* https://starship.rs/ seems interesting.

== Text Editor / IDE

For text editing and writing code I use Neovim.
When I need an IDE I use VS Code.
My favorite editor for Jupyter notebooks is Google Colaboratory.

. NetBeans
. Sublime Text
. Notepad++
. VS Code
. Vim
. Neovim
. https://github.com/zed-industries/zed[Zed] (TODO)

== Version control

I use git with both github and gitlab hosting.

== Markdown Format

Currently I use Asciidoc for note taking. It has high expressive power while being well defined.

== Internet browser

* google-chrome
* chromium

== Video Player

https://www.videolan.org/vlc/

== Eye Strain

I use following settings to lower my eye strain.

. Light theme instead of a dark theme.
    * It's way less *cool* and that's the point _wink_.
. Exponential brightness step count in power manager.
    * It allows you to set the display really dim during nights.
. Use a software which lowers the screen temperature.
    * http://jonls.dk/redshift/
    * https://justgetflux.com/

== Presentations

* https://revealjs.com/
