= Text Specifications
:keywords: text, format, csv, yaml, json, xml, html, tex, asciidoc, markdown, regex
:hide-uri-scheme:
:toc:

== About

Good specification of text format has many use cases.

|===
| Use Case | Examples

| Data storage / transfer | csv, yaml, toml, xml, json, xls
| Markup langauge | html, xml, markdown, asciidoc, rst, tex
| Styling | css, scss
| Pattern matching | regex
|===

== Encoding

=== BOM

    The byte order mark (BOM) is a particular usage of the special Unicode character, U+FEFF BYTE ORDER MARK

quoted from: https://en.wikipedia.org/wiki/Byte_order_mark

.UTF-8 BOM
----
0xEF,0xBB,0xBF
----

.UTF-16 BOM
----
U+FEFF
----

== Conversion Between Formats

Good format specification has many advantages.
Among others, it allows to convert the document from one format to another.
This can be done automatically using a conversion tool.
When the target format has equal or greater expression power the conversion is lossless.

=== Pandoc

https://pandoc.org/[Pandoc a universal document converter]

Installation

[source, shell]
----
wget "https://github.com/jgm/pandoc/releases/download/2.11.4/pandoc-2.11.4-1-amd64.deb"
sudo dpkg -i pandoc-2.11.4-1-amd64.deb
----

https://github.com/jgm/pandoc/releases/[Pandoc releases (github.com)]

*Basic usage*

* https://pandoc.org/demos.html[Demos (pandoc.org)]

Convert markdown to PDF

[source, shell]
----
pandoc report.md --pdf-engine=xelatex -o report.pdf
----

Convert markdown to HTML

[source, shell]
----
# HTML fragment (plain html)
pandoc page.md -o page.html

# HTML with style (-s for standalone)
pandoc -s page.md -o page.html

# Add advanced LaTeX math
pandoc -s page.md --mathjax -o page.html
----

* https://tex.stackexchange.com/questions/551960/pandoc-cannot-parse-equation-with-a-fraction[use --mathjax (tex.stackexchange.com)]
